foodonlineproject/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.conf import settings
from django.conf.urls.static import static


from marketplace import views as Maeketviews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='home'),
    path('accounts/',include('accounts.urls')),
    path('vendor/',include('vendor.urls')),
    path('menuapp/',include('menuapp.urls')),
    path('marketplace/',include('marketplace.urls')),
    path('customer/',include('customer.urls')),
    
    path('cart/',Maeketviews.cart,name='cart'),
    path('search/',Maeketviews.search,name='search')
    # path("__debug__/", include("debug_toolbar.urls")),
    # path('geoocode/',views.geoocode)
   
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

menuapp/urls.py
from django.urls import path

urlpatterns = [
    
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


from django.db.models import Q


class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, password=None):
        if not email:
            raise ValueError('You should give an email')
        if not username:
            raise ValueError('You should provide a proper name')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, first_name=first_name, last_name=last_name)
        user.set_password(password)
        user.is_active = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, first_name, last_name, password=None):
        email = self.normalize_email(email)
        user = self.create_user(email, username, first_name, last_name, password)
        user.is_admin = True
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class Custom_User(AbstractBaseUser, PermissionsMixin):
    VENDOR = 1
    CUSTOMER = 2
    ROLE_CHOICES = (
        (VENDOR, 'RESTAURANT'),
        (CUSTOMER, 'CUSTOMER')
    )

    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=12, blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, blank=True, null=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    def get_role(self):
        user_role = ''
        if self.role == self.VENDOR:
            user_role = 'RESTAURANT'
        elif self.role == self.CUSTOMER:
            user_role = 'CUSTOMER'
        return user_role


class Userprofile(models.Model):
    user = models.OneToOneField('Custom_User', on_delete=models.CASCADE)
    profile_pictutre=models.ImageField(upload_to='user/profile_pictures',blank=True,null=True)
    cover_photo=models.ImageField(upload_to='user/cover_pictures',blank=True,null=True)
    addressline_1=models.CharField(max_length=50,blank=True,null=True)
    addressline_2=models.CharField(max_length=50,blank=True,null=True)
    city=models.CharField(max_length=15,blank=True,null=True)
    state=models.CharField(max_length=15,blank=True,null=True)
    pincode=models.CharField(max_length=20,null=True,blank=True)
    longtitude=models.CharField(max_length=20,null=True,blank=True)
    latitude=models.CharField(max_length=20,null=True,blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)
    
    
    
    # def get_queryset(self):
    #     return Userprofile.objects.filter(Q(longtitude__icontains=85.0) | Q(latitude__icontains=20.0))
    
    def __str__(self):
        return self.user.email
    
    def full_address(self):
        return f"{self.addressline_1},{self.addressline_2}"
    


@receiver(post_save, sender=Custom_User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Userprofile.objects.create(user=instance)
        print('User profile created')
    else:
        try:
            user_profile = Userprofile.objects.get(user=instance)
            # Update user_profile fields here if needed
            user_profile.save()
            print('User profile updated successfully')
        except Userprofile.DoesNotExist:
            Userprofile.objects.create(user=instance)
            print('User profile created because it was not available before')



# post_save.connect(post_save_create_profile_receiver,sender=Custom_User)

# use this decorator instead of manually write the code 

accounts/forms.py
from django import forms

from .models import Custom_User,Userprofile
from django.shortcuts import render
from .custom_validation import valid_file




class Userform(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model=Custom_User
        fields=['first_name','last_name','username','email','password','confirm_password']
        
        
    def clean(self):
        clean_data=super(Userform,self).clean()
        password=clean_data.get('password')
        confirm_password=clean_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError('password Does not match')
          
          
class Userprofile_form(forms.ModelForm):
    profile_pictutre=forms.FileField(widget=forms.FileInput(attrs={'class':'btn btn-info'}),validators=[valid_file])
    cover_photo=forms.FileField(widget=forms.FileInput(attrs={'class':'btn btn-info'}),validators=[valid_file])
    
    longtitude=forms.FloatField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    latitude=forms.FloatField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    
    # there is an alternate method avalable by iteratine the fields 
    
    # addressline_1 = forms.CharField(widget=forms.TextInput(attrs={'id': 'ipaddress'}), max_length=50)
    # customization needed otherwise wen you aplied the autocomplete the it will take 
    # id_adreesline1 by default 

    
    class Meta:
        model = Userprofile
        fields=['profile_pictutre','cover_photo','addressline_1','addressline_2','city','state','pincode',
              'longtitude','latitude', ]
        
        
    # in the big project it is best 
    # def __init__(self,*args,**kwargs):
    #     super(Userprofile_form,self).__init__(*args)
        
    #     for field in self.fields:
    #         if  field=='longtitude' or field=='latitude':
    #               self.fields[field].widget.attrs['readonly']='readonly'
        
        
        
    # def user_profile_save(self,commit=True):
    #     user=super(Userprofile_form,self).save(commit=False)
    #     if commit:
    #         vendor_update(self)
    #         user.save() 
            
    #     return user
   
class Userinfoform(forms.ModelForm):
    class Meta:
        model=Custom_User
        fields=['first_name', 'last_name', 'phone_number']
    

templates/base.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FoodOnline</title>

	<link rel="stylesheet" type="text/css" href="https://common.olemiss.edu/_js/sweet-alert/sweet-alert.css">
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<!-- CSS -->
	<link href="{% static  'css/iconmoon.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}"     rel="stylesheet">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="{% static 'css/bootstrap-slider.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/custom.css'%}">
	<link rel="stylesheet"  href="{% static 'css/add_cat.css' %}"
	<link rel="stylesheet" href="sweetalert2.min.css">
	<script src="{% static 'js/custom.js' %}"></script>



	<!-- js0 -->
	<script src="https://common.olemiss.edu/_js/sweet-alert/sweet-alert.min.js"></script>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

	<script src="{% static  'js/modernizr.js' %}"></script>
	<script src="{% static   'js/bootstrap.js' %}"></script>
	







    <script src="{% static 'js/jquery.js'%}"></script>

	<script src="https://maps.googleapis.com/maps/api/js?key={{ Googleapi }}&libraries=places&callback=initAutoComplete" async defer></script>

    
	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
		.photo img {
			height: 30px;  /* Set a reasonable height */
			width: 30px;   /* Set a reasonable width */
		}
		.photo {
			display: inline-block;  /* Ensure the anchor behaves like a block-level element */
			width: 30px;            /* Set the width */
			height: 30px;           /* Set the height */
			background-size: cover;  /* Adjust the background size as needed */
		}
		
		
		
	</style>
</head>

<body>
     

    {% include "includes/navbar.html" %}

    {% block content %}


    {% endblock %}




    {% include "includes/footer.html" %}




    <!-- load navbar -->

    <!-- load content here  -->

    <!-- load fotter here  -->


			<!-- Choose From Most Popular Listing End -->

			<!-- Home Pages Elements End  -->

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
		<!-- Main Section Start -->
		<div class="main-section">
			<!-- Home Pages Elements Strat -->
			<!-- Main Search Start -->
			<div class="page-section nopadding cs-nomargin" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static 'extra-images/bg-image1.jpg' %}) no-repeat center / cover;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="element-title">
								<h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
									We are in the business of food<br>our restaurants do</h1>
								<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
									Ridiculus sociosqu
									cursus neque cursus curae ante scelerisque vehicula.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="main-search fancy bg-holder">
								<form action="{% url 'search' %}"    method="GET">
									         {% csrf_token %}
									<div class="row">
										<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
											<div class="field-holder">
												<input type="text" name="keyword" placeholder="Resturant name or foodname" value="">
											</div>
										</div>
										<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
											<div class="field-holder">
												<ul>
													<li class="select-location">
														<div class="foodbakery-locations-fields-group foodbakery-focus-out">
															<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
															<span id="foodbakery_radius_location_open333" class="foodbakery-radius-location"><i class="icon-target5"></i></span>
															<input type="text " name="addressmine" id="id_addressline_1" class="location-field-text filter" style="height: 50px; width:351px;text-align:center" placeholder="All Locations">
															<input type=hidden name="lat" id="id_longtitude" value="">
															<input type=hidden name="lan" id="id_latitude" value="">



														</div>
														<div class="select-location" id="foodbakery-radius-range333" style="display: none;">
															<div class="select-popup popup-open">
																<a id="location_close_popup333" href="javascript:0;" class="location-close-popup">
																
																	<i class="icon-times"></i></a>
																<input type="hidden" class="foodbakery-radius" name="foodbakery_radius" value="10">
																<p>Show with in</p>
																<input id="ex16b333" type="text" data-value="10" value="10" style="display: none;">
																<script>
																	jQuery(document).ready(function () {
																		var elem = jQuery("#ex16b333");
																		if (elem.length != "") {
																			elem.slider({
																				step: 1,
																				min: 0,
																				max: 500,
																				value: 10,
																			});
																			elem.on("slideStop", function () {
																				var rang_slider_val = elem.val();
																				jQuery("#ex16b333CurrentSliderValLabel").html(rang_slider_val);
																				jQuery("#range-hidden-foodbakery-radius333").val(rang_slider_val);
																				//foodbakery_restaurant_content("333");
																			});
																			elem.on("slide", function () {
																				jQuery("#ex16b333CurrentSliderValLabel").html(elem.val());
																			});
																		}

																		$("#foodbakery_radius_location_open333").click(function () {
																			$("#foodbakery-radius-range333").show();
																		});
																		$("#location_close_popup333").click(function () {
																			$("#foodbakery-radius-range333").hide();
																		});
																	});
																</script>
																<span>Miles: <span id="ex16b333CurrentSliderValLabel">10</span></span><br>
																<p class="my-location">of <i class="cs-color icon-location-arrow"></i><a id="foodbakery-geo-location-all" class="cs-color foodbakery-geo-location313324" href="javascript:void(0)">My location</a></p>
															</div>
														</div>
													</li>
												</ul>
											</div>
										</div>

										<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2" style="padding: ;">
											<select name="radius" id="radius" style="height: 50px;" required>
												   <option value="" selected>Chose radius</option>
												   <option>10km</option>
												   <option>20km</option>
												   <option>30km</option>
												   <option>40km</option>
											</select>

										</div>



										<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
											<div class="field-holder">
												<input type="submit" value="Search">
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
						
					</div>
				</div>
			</div>
			<!-- Main Search End -->
			
			<!-- Top Restarurants Section Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" >
							<div class="element-title align-left">
								<h2>Top Restaurants</h2>
								<p>Explore restaurants, bars, and cafés by locality</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="padding-right:0 !important; padding-left:0 !important">
							<div class="company-logo">
								<ul>
									{% for vendor in vendors %}
									<li class="has-border">
										<figure>
											{% if vendor %}
											<a href="#"><img src="{{vendor.user_profile.profile_pictutre.url}}" class="attachment-full size-full wp-post-image" alt=""></a>

											{% else %}
											<a href="#"><img src="{% static 'extra-images/listing-logo18.png' %}" class="attachment-full size-full wp-post-image" alt=""></a>
											{% endif %}
										</figure>
									</li>
									{% endfor %}
									
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- Top Restarurants Section End -->
			<!-- Choose From Most Popular Listin Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-center">
								<h2>Choose From Most Popular Restaurants</h2>
								<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="listing fancy">
								<ul class="row">
									{% for vendor in vendors %}
									<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
										<div class="list-post featured">
											<div class="img-holder">
												<figure><a href="#"><img src="{% static  'extra-images/listing-logo18.png' %}" class="img-thumb wp-post-image" alt=""></a></figure>
												{% if vendor.is_open %}
												<span class="restaurant-status open">
													<em class="bookmarkRibbon"></em>Open
												</span>

												{% else %}
												<span class="restaurant-status close">
													<em class="bookmarkRibbon"></em>Close
												</span>

											    {% endif %}


											</div>
											<div class="text-holder">
												<div class="list-rating">
													<div class="rating-star">
														<span class="rating-box" style="width: 100%;"></span>
													</div>
													<span class="reviews">(1)</span>
												</div>
												<div class="post-title">
													<h5>
														<a href="listing-detail.html">Restaurant Demo</a>
														<span class="sponsored text-color">Sponsored</span>
													</h5>
												</div>
												<address> <span>Type of food : </span> Apple Juice</address>
											</div>
											
										</div>
									</li>

								    {% endfor %}

								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>


</div>

{% endblock %}